### ISSUE TITLE
fix app download button.  apple has the css somewhere on their site.

### ISSUE THREAD

**Issue by courtlandgaba** [geekin-radio/geekin#21]

**Comment by brentoneill** [comment]
@courtlandgaba  Looks like you fixed this recently? Do we need to make this button appear in the footer as well?

**Comment by courtlandgaba** [comment]
@brentoneill hmmmmm, probably.  i sort of fixed it. i think there's a way to make it bigger. i tried to change the inline-styling but it didn't help

**Comment by brentoneill** [comment]
Not sure how to make it larger at the moment, but it is centered now.
